/**
 * Tree type samples for the structure lots (design sample, not generated by a model).
 * Usage: npx tsx scripts/build-tree-types-sample.ts → docs/國策樹型-範例.html
 * Six hand-made trees, one per tree type, drawn in the medal style with the real layoutTree.
 */
import { writeFileSync } from 'node:fs';
import { drawTree, f, samplePage, styles, type Tree } from './sample-kit';

type Sample = { key: string; name: string; naming: string; traits: string[]; lots: string[]; tree: Tree };

const samples: Sample[] = [
  {
    key: 'build',
    name: '发展型',
    naming: '公文式',
    traits: [
      '建设与制度逐步累积；核心分支承载本期主要目的，两条侧翼处理并行事务',
      '共同开局后分岔成两条互斥路线，汇流到同一终点',
      '多数国策产出能力或承诺，后项以前项的成果为条件',
    ],
    lots: [
      '开局：两项连续开局',
      '分岔：第 2 层',
      '路线：2 条，等长',
      '终局：汇流单一终点',
      '侧翼：短直链 ×2',
      '节奏：均匀',
    ],
    tree: {
      title: '苍海同盟·港务新章',
      core: '港务新章',
      mutex: [['d3', 'd4']],
      focuses: [
        f('s1', '巡查海岸炮台', '海防整备', 'army', 14, [], 'completed'),
        f('s2', '增设灯塔哨所', '海防整备', 'army', 21, [['s1']], 'available'),
        f('d1', '召集港务会议', '港务新章', 'crown', 14, [], 'completed'),
        f('d2', '清点泊位与仓栈', '港务新章', 'industry', 14, [['d1']], 'active', { progress: 50 }),
        f('d3', '扩建北堤船坞', '港务新章', 'industry', 21, [['d2']], 'locked', { head: true }),
        f('d4', '开放自由贸易区', '港务新章', 'trade', 21, [['d2']], 'locked', { head: true }),
        f('d5', '招募造船工匠', '港务新章', 'industry', 21, [['d3']], 'locked'),
        f('d6', '制定关税减免章程', '港务新章', 'trade', 21, [['d4']], 'locked'),
        f('d7', '试造远洋商船', '港务新章', 'science', 28, [['d5']], 'locked'),
        f('d8', '招徕外商会馆', '港务新章', 'diplomacy', 28, [['d6']], 'locked'),
        f('d9', '颁布港务新章', '港务新章', 'crown', 21, [['d7', 'd8']], 'locked', { pivotal: true }),
        f('t1', '设立航海学舍', '学舍育才', 'science', 21, [], 'available'),
        f('t2', '编订近海海图', '学舍育才', 'science', 14, [['t1']], 'locked'),
      ],
    },
  },
  {
    key: 'choice',
    name: '抉择型',
    naming: '四字意象式',
    traits: [
      '叙事决策树：每个国策都是一次政治转折，没有侧翼',
      '先选大路线，再在大路线里二选一（两层互斥），子路线汇合后各自走向不同结局',
      '两条大路线不汇流：本期以其中一个结局收束，走到任一结局即完成本期目的',
    ],
    lots: [
      '开局：两项连续开局',
      '分岔：第 2 层',
      '互斥：路线内再有一组小互斥',
      '路线内部：中段二选一后汇合',
      '终局：各自终点',
      '侧翼：无',
      '命名：四字意象',
    ],
    tree: {
      title: '北境联邦·冰河将裂',
      core: '冰河将裂',
      mutex: [
        ['c3', 'c4'],
        ['c5', 'c6'],
        ['c7', 'c8'],
      ],
      focuses: [
        f('c1', '雪原将融', '冰河将裂', 'crown', 14, [], 'completed'),
        f('c2', '长夜议事', '冰河将裂', 'diplomacy', 7, [['c1']], 'completed'),
        f('c3', '薪火相传', '冰河将裂', 'crown', 21, [['c2']], 'available', { head: true }),
        f('c4', '破冰而行', '冰河将裂', 'science', 21, [['c2']], 'available', { head: true }),
        f('c5', '歃血为盟', '冰河将裂', 'army', 21, [['c3']], 'locked', { head: true }),
        f('c6', '化干为玉', '冰河将裂', 'diplomacy', 21, [['c3']], 'locked', { head: true }),
        f('c7', '铁律新章', '冰河将裂', 'crown', 21, [['c4']], 'locked', { head: true }),
        f('c8', '市井之声', '冰河将裂', 'trade', 21, [['c4']], 'locked', { head: true }),
        f('c9', '冬约重订', '冰河将裂', 'diplomacy', 28, [['c5', 'c6']], 'locked'),
        f('c10', '风雪改元', '冰河将裂', 'crown', 28, [['c7', 'c8']], 'locked'),
        f('c11', '万山同心', '冰河将裂', 'crown', 21, [['c9']], 'locked', { pivotal: true }),
        f('c12', '前路未明', '冰河将裂', 'science', 21, [['c10']], 'locked', { pivotal: true }),
      ],
    },
  },
  {
    key: 'crisis',
    name: '危机型',
    naming: '口号式',
    traits: [
      '开局就是危机，首项需要剧情取得的外部成果才能完成',
      '前段是两件必须同时完成的急务（「且」前置），撑过之后才分岔',
      '两条路线是「撑过去」的不同方式，各自收束成妥协或铁腕的结局；一条短侧翼处理次生灾害',
    ],
    lots: [
      '开局：危机开局',
      '开局：双起点并行后汇合',
      '分岔：第 3 层',
      '路线：一短一长',
      '终局：各自终点',
      '侧翼：短直链',
      '命名：口号式',
    ],
    tree: {
      title: '河谷王国·大坝溃堤',
      core: '撑过这个冬天',
      mutex: [['k4', 'k5']],
      focuses: [
        f('k1', '大坝溃堤！', '撑过这个冬天', 'industry', 7, [], 'waiting', { progress: 100 }),
        f('k2', '封锁下游三郡', '撑过这个冬天', 'army', 7, [['k1']], 'locked'),
        f('k2b', '征调全国粮仓', '撑过这个冬天', 'trade', 14, [['k1']], 'locked'),
        f('k3', '撑过第一个冬天', '撑过这个冬天', 'crown', 21, [['k2'], ['k2b']], 'locked'),
        f('k4', '向帝国借款', '撑过这个冬天', 'diplomacy', 14, [['k3']], 'locked', { head: true }),
        f('k5', '以工代赈', '撑过这个冬天', 'industry', 28, [['k3']], 'locked', { head: true }),
        f('k6', '割让盐矿开采权', '撑过这个冬天', 'trade', 21, [['k4']], 'locked'),
        f('k7', '镇压粮价暴动', '撑过这个冬天', 'army', 14, [['k5']], 'locked'),
        f('k8', '苟全国格', '撑过这个冬天', 'diplomacy', 14, [['k6']], 'locked', { pivotal: true }),
        f('k9', '铁腕重建', '撑过这个冬天', 'crown', 21, [['k7']], 'locked', { pivotal: true }),
        f('p1', '隔离疫区', '瘟疫防线', 'science', 7, [], 'available'),
        f('p2', '求援教会医团', '瘟疫防线', 'diplomacy', 14, [['p1']], 'locked'),
      ],
    },
  },
  {
    key: 'reform',
    name: '改革型',
    naming: '公文式',
    traits: [
      '长主干分阶段推进：试行 → 推广 → 定制',
      '推广阶段出现反对派造成的分岔：强推或妥协，汇流后再延伸一项落实',
      '侧翼处理舆论与反对派，它的成果是「妥协」路线的条件（跨分支前置）',
    ],
    lots: [
      '开局：单项开局',
      '分岔：第 3 层（主干较长）',
      '路线：2 条，一长一短',
      '终局：汇流后延伸',
      '侧翼：成果是核心某项的条件',
      '重要国策：终点',
    ],
    tree: {
      title: '奥古斯提姆帝国·清丈田亩',
      core: '清丈田亩',
      mutex: [['r4', 'r5']],
      focuses: [
        f('r1', '清丈试行令', '清丈田亩', 'crown', 14, [], 'completed'),
        f('r2', '试点三州清丈', '清丈田亩', 'industry', 21, [['r1']], 'completed'),
        f('r3', '清丈结果公示', '清丈田亩', 'science', 14, [['r2']], 'active', { progress: 30 }),
        f('r4', '强推全国清丈', '清丈田亩', 'army', 28, [['r3']], 'locked', { head: true }),
        f('r5', '与旧贵族妥协', '清丈田亩', 'diplomacy', 21, [['r3'], ['o2']], 'locked', { head: true }),
        f('r6', '废除免税特权', '清丈田亩', 'crown', 28, [['r4']], 'locked'),
        f('r7', '保留祖产豁免', '清丈田亩', 'trade', 14, [['r5']], 'locked'),
        f('r8', '新田赋定制', '清丈田亩', 'crown', 21, [['r6', 'r7']], 'locked', { pivotal: true }),
        f('r9', '设立田赋监察司', '清丈田亩', 'science', 14, [['r8']], 'locked'),
        f('o1', '安抚贵族议院', '舆论与反对', 'diplomacy', 14, [], 'available'),
        f('o2', '拉拢地方豪强', '舆论与反对', 'trade', 21, [['o1']], 'locked'),
      ],
    },
  },
  {
    key: 'chess',
    name: '棋局型',
    naming: '混合（关键抉择用意象，其余公文）',
    traits: [
      '对外选边：开局后立刻三分，每条路线对应一个外部势力',
      '三条路线各自走到自己的结局（成为谁的藩篱、谁的盟友，或中立之城）',
      '情报侧翼的成果是中立路线中段的条件，路线之间互相牵制',
    ],
    lots: [
      '开局：单项开局',
      '分岔：开局后立刻',
      '路线：3 条',
      '路线交互：中立路线需要侧翼成果',
      '终局：各自终点',
      '侧翼：成果是核心某项的条件',
    ],
    tree: {
      title: '王冠七省·列强环伺',
      core: '列强环伺',
      mutex: [['g2', 'g3', 'g4']],
      focuses: [
        f('g1', '列强环伺', '列强环伺', 'crown', 14, [], 'completed'),
        f('g2', '倚帝国之盾', '列强环伺', 'army', 21, [['g1']], 'available', { head: true }),
        f('g3', '严守中立', '列强环伺', 'diplomacy', 21, [['g1']], 'available', { head: true }),
        f('g4', '联北境之盟', '列强环伺', 'diplomacy', 21, [['g1']], 'available', { head: true }),
        f('g5', '接受帝国驻军', '列强环伺', 'army', 28, [['g2']], 'locked'),
        f('g6', '两面周旋', '列强环伺', 'trade', 21, [['g3'], ['i2']], 'locked'),
        f('g7', '共享山口关税', '列强环伺', 'trade', 21, [['g4']], 'locked'),
        f('g8', '帝国藩篱', '列强环伺', 'crown', 21, [['g5']], 'locked', { pivotal: true }),
        f('g9', '中立之城', '列强环伺', 'crown', 28, [['g6']], 'locked', { pivotal: true }),
        f('g10', '北境同盟议席', '列强环伺', 'crown', 28, [['g7']], 'locked', { pivotal: true }),
        f('i1', '收买双方使节', '情报网', 'science', 14, [], 'available'),
        f('i2', '截获密约', '情报网', 'science', 21, [['i1']], 'locked'),
      ],
    },
  },
  {
    key: 'dual',
    name: '双轨型',
    naming: '公文式',
    traits: [
      '核心与一条同等分量的强侧翼并行，两边交替提供条件（跨分支前置）',
      '核心只有一组小互斥（东线或西线优先）；终点同时需要两条轨道的成果',
      '适合需要两个系统一起长成的议程，例如铁路与钢铁',
    ],
    lots: [
      '开局：双起点并行（核心与侧翼各一）',
      '路线交互：两轨交替互为条件',
      '互斥：一组小互斥',
      '终局：汇流单一终点',
      '侧翼：强侧翼 ×1',
    ],
    tree: {
      title: '苍海同盟·铁轨与钢炉',
      core: '干线铁路',
      mutex: [['l2', 'l3']],
      focuses: [
        f('l1', '勘定干线', '干线铁路', 'science', 14, [], 'completed'),
        f('l2', '东线优先', '干线铁路', 'industry', 21, [['l1']], 'available', { head: true }),
        f('l3', '西线优先', '干线铁路', 'industry', 21, [['l1']], 'available', { head: true }),
        f('l4', '铺设首段钢轨', '干线铁路', 'industry', 28, [['l2', 'l3'], ['m2']], 'locked'),
        f('l5', '铁路运煤专线', '干线铁路', 'trade', 21, [['l4']], 'locked'),
        f('l6', '全国铁路贯通', '干线铁路', 'crown', 28, [['l5'], ['m4']], 'locked', { pivotal: true }),
        f('m1', '开采赤铁矿', '钢铁工业', 'industry', 14, [], 'completed'),
        f('m2', '扩建高炉', '钢铁工业', 'industry', 21, [['m1']], 'active', { progress: 60 }),
        f('m3', '以煤炼钢', '钢铁工业', 'science', 21, [['m2'], ['l5']], 'locked'),
        f('m4', '钢轨自给', '钢铁工业', 'industry', 28, [['m3']], 'locked'),
      ],
    },
  },
];

const medal = styles.find((style) => style.key === 'medal')!;
const nav = samples
  .map(
    (sample, index) =>
      `<button data-show="${sample.key}" aria-pressed="${index === 0}">${sample.name}</button>`,
  )
  .join('');
const main = samples
  .map(
    (sample, index) => `<section data-style="${sample.key}" ${index ? 'hidden' : ''}>
  <div class="type-card"><h2>${sample.name}<small>命名：${sample.naming}</small></h2>
  <ul>${sample.traits.map((t) => `<li>${t}</li>`).join('')}</ul>
  <p class="lots">${sample.lots.map((lot) => `<span>${lot}</span>`).join('')}</p></div>
  ${drawTree(medal, sample.tree)}
</section>`,
  )
  .join('');
const header = `<h1>国策树型范例（样品，由人工编写，未改生成规则）</h1>
<p>六种树型各一棵，用勋章式与正式排版画出。每张卡片说明树型特征、命名风格与对应的结构签；签只是倾向，实际生成时由模型依国情诠释。蓝色连线是跨分支前置，虚线是「或」前置，红色点线连接同组互斥路线。</p>
<div class="switch">${nav}</div>`;
const script = `for (const button of document.querySelectorAll('[data-show]')) {
  button.addEventListener('click', () => {
    for (const other of document.querySelectorAll('[data-show]')) other.setAttribute('aria-pressed', String(other === button));
    for (const section of document.querySelectorAll('[data-style]')) section.hidden = section.dataset.style !== button.dataset.show;
    history.replaceState(null, '', '#' + button.dataset.show);
  });
}
document.querySelector('[data-show="' + location.hash.slice(1) + '"]')?.click();`;
const extraCss = `<style>
.type-card { margin: 18px 0 4px; padding: 12px 16px; max-width: 980px; border: 1px solid rgba(217, 191, 120, 0.22); border-radius: 10px; background: rgba(25, 34, 29, 0.8); }
.type-card h2 { margin: 0 0 6px; font: 600 17px var(--serif); color: var(--gold); letter-spacing: 0.08em; }
.type-card h2 small { margin-left: 12px; font: 400 12.5px var(--sans); color: var(--muted); letter-spacing: 0; }
.type-card ul { margin: 0; padding-left: 18px; color: var(--text); font-size: 13px; line-height: 1.7; }
.lots { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0 0; }
.lots span { font-size: 11.5px; padding: 2px 8px; border-radius: 10px; color: #e5d3a0; background: rgba(220, 194, 124, 0.08); border: 1px solid rgba(220, 194, 124, 0.28); }
</style>`;
const html = samplePage('国策树型范例', header, extraCss + main, script);
writeFileSync(new URL('../docs/國策樹型-範例.html', import.meta.url), html);
console.log('written docs/國策樹型-範例.html');
