export default {
  crisis: {
    first: [
      {
        id: 'A01',
        title: '北境商路总核查',
        icon: 'scroll',
        x: 482,
        y: 55,
        requires: [],
        description:
          '信用争议延烧到渡鸦港。朝廷必须先知道，帝国与北境究竟欠了彼此多少，以及哪一条商路一旦中断，会先让自己的城市缺粮。',
        effect: '核查报告呈交，取得欠款、货源与航运依赖的决策依据。',
        status: 'done',
      },
      {
        id: 'A02',
        title: '冻结新增官方信用',
        icon: 'scale',
        x: 482,
        y: 195,
        requires: [['A01']],
        description:
          '皇家印信不再为新一批北境交易背书。既有契约仍有处理窗口，但任何新的风险，都不能再由朝廷默默承担。',
        effect: '暂停新增官方担保；已签契约另行处理。',
        status: 'done',
      },
      {
        id: 'A03',
        title: '民生日用豁免表',
        icon: 'grain',
        x: 172,
        y: 335,
        requires: [['A02']],
        description:
          '边境可以停止奢侈品通行，却不能停止百姓吃饭。粮食与药材将得到明确豁免，避免地方关口自行扩大禁令。',
        effect: '公布基本粮食、药材的豁免与受理办法。',
        status: 'done',
      },
      {
        id: 'A05',
        title: '旧债另案清理',
        icon: 'scroll',
        x: 792,
        y: 335,
        requires: [['A02']],
        description:
          '旧债不会因一句冻结命令消失。朝廷将逐笔核验欠款，把真实损失、投机押注与外交筹码分开处理。',
        effect: '建立既有债务申报、核验与交涉程序。',
        status: 'available',
      },
      {
        id: 'A04',
        title: '渡鸦港粮运统筹',
        icon: 'ship',
        x: 172,
        y: 480,
        requires: [['A03']],
        description:
          '渡鸦港从不缺少帐簿，缺的是愿意对同一批粮食负责的人。港务官把延误归咎于商人，商人指向领主，领主则抱怨军方征用。朝廷将把船位、仓储与转运纳入同一份调度规程。',
        effect: '粮运统筹规程生效，指定跨部门责任；实际运粮由事件继续追踪。',
        days: 18,
        total: 30,
        status: 'active',
      },
      {
        id: 'A06',
        title: '定向禁运清单',
        icon: 'shield',
        x: 677,
        y: 480,
        requires: [['A05']],
        description: '施压必须指向能够承受压力的人。限制指定货物与交易对象，保留帝国仍然需要的商路。',
        effect: '禁运清单生效；不代表对方已经让步。',
        mutex: 'A07',
        status: 'locked',
      },
      {
        id: 'A07',
        title: '限期交涉训令',
        icon: 'scale',
        x: 907,
        y: 480,
        requires: [['A05']],
        description: '使节带走的不只是抗议，也是期限与底线。朝廷仍为协议留出位置，但不再接受无止境的拖延。',
        effect: '授权使节依明确底线展开交涉。',
        mutex: 'A06',
        status: 'locked',
      },
      {
        id: 'A08',
        title: '西境军需优先',
        icon: 'shield',
        x: 57,
        y: 625,
        requires: [['A04']],
        description: '军方要求船位先装载军需。让步的会是城市粮商，而朝廷必须承担这项选择带来的民生压力。',
        effect: '紧缺船位优先供军需调度。',
        mutex: 'A09',
        status: 'locked',
      },
      {
        id: 'A09',
        title: '平民粮运保留额',
        icon: 'grain',
        x: 287,
        y: 625,
        requires: [['A04']],
        description: '城市的面包不能只靠军需官的余裕。朝廷将为平民粮运留出底线，让征用也必须有所节制。',
        effect: '建立民用最低运量；军需使用其余船位。',
        mutex: 'A08',
        status: 'locked',
      },
      {
        id: 'A10',
        title: '过境联查规程',
        icon: 'scroll',
        x: 677,
        y: 625,
        requires: [['A06']],
        description: '同一份禁令不该在十座关口变成十种收费。联查规程将约束查验，也为被扣货物提供申诉办法。',
        effect: '统一禁运查验与申诉程序。',
        status: 'locked',
      },
      {
        id: 'A11',
        title: '有条件恢复清算',
        icon: 'scale',
        x: 907,
        y: 625,
        requires: [['A07']],
        description: '印信可以重新落在票据上，但必须先看见对方履行承诺。清算恢复将以核验条件为限。',
        effect: '对方实际接受并履行条款后，恢复部分信用清算。',
        condition: '交涉已取得实际成果',
        status: 'locked',
      },
      {
        id: 'A12',
        title: '北境贸易新秩序',
        icon: 'star',
        x: 482,
        y: 765,
        requires: [
          ['A10', 'A11'],
          ['A08', 'A09'],
        ],
        description:
          '临时措施终究需要一个终点。依所选路线确立常态贸易与粮运规则，让每一艘船不必等待新的御前命令。',
        effect: '本轮贸易与粮运制度安排告一段落；旧债回收等事件继续推进。',
        status: 'locked',
      },
    ],
    second: [
      {
        id: 'A04',
        title: '渡鸦港粮运统筹',
        icon: 'ship',
        x: 482,
        y: 55,
        requires: [],
        description:
          '渡鸦港从不缺少帐簿，缺的是愿意对同一批粮食负责的人。港务官把延误归咎于商人，商人指向领主，领主则抱怨军方征用。朝廷将把船位、仓储与转运纳入同一份调度规程。',
        effect: '粮运统筹规程生效，指定跨部门责任；实际运粮由事件继续追踪。',
        days: 18,
        total: 30,
        inherited: true,
        status: 'active',
      },
      {
        id: 'B02',
        title: '救援物资特别许可',
        icon: 'cross',
        x: 137,
        y: 195,
        requires: [],
        description: '边境同时涌入求援信与承运申请。救援需要专门窗口，也需要有人对货物确实送达负责。',
        effect: '建立跨境救援申请、查验与承运责任。',
        status: 'available',
      },
      {
        id: 'B03',
        title: '暂缓新增贸易限制',
        icon: 'scale',
        x: 137,
        y: 335,
        requires: [['B02']],
        description: '裂隙没有在国界前停下。朝廷将暂缓扩大施压，为救援交易设置有限例外；既有争议仍须处理。',
        effect: '暂停新增限制；救援以外的信用冻结仍有效。',
        status: 'locked',
      },
      {
        id: 'B07',
        title: '境内接济与转运站',
        icon: 'grain',
        x: 827,
        y: 335,
        requires: [['B02']],
        description:
          '逃离灾区的人需要暂住之所，救援粮也需要转运之地。地方责任不能只写在一纸没有预算的命令里。',
        effect: '核定接济网络、预算与责任；站点建设由事件追踪。',
        status: 'locked',
      },
      {
        id: 'B04',
        title: '边境联合报灾',
        icon: 'scroll',
        x: 137,
        y: 480,
        requires: [['B03']],
        description: '两国各自掌握一半消息，就可能重复救援一座城，却遗漏另一座。先从交换可以核实的灾情开始。',
        effect: '建立灾情交换渠道并完成首轮互报。',
        condition: '合作方实际接受灾情交换',
        status: 'locked',
      },
      {
        id: 'B10',
        title: '灾时粮运优先序',
        icon: 'ship',
        x: 827,
        y: 625,
        requires: [['A04'], ['B07']],
        description:
          '军队、城市与灾区都说自己的粮船不能再等。既有统筹规程将承接新的分配次序，而代价必须公开交代。',
        effect: '确立民生、救援与军需的灾时配额。',
        status: 'locked',
      },
      {
        id: 'B05',
        title: '开放联合救援',
        icon: 'cross',
        x: 22,
        y: 625,
        requires: [['B04']],
        description:
          '联盟药材停在边境，帝国粮船等候靠岸。双方都愿意救人，也都不愿先让自己的印信失去效力。协议必须说清楚，谁排定次序、谁查验货舱，又由谁负责。',
        effect: '合作方签署并启用共同调度与查验安排。',
        mutex: 'B06',
        condition: '合作方接受共同救援协议',
        status: 'locked',
      },
      {
        id: 'B06',
        title: '帝国主持援助',
        icon: 'shield',
        x: 252,
        y: 625,
        requires: [['B04']],
        description:
          '援助可以跨越边境，指挥权则留在帝国手中。这会保住主导权，也意味著更多支出与责任由朝廷承担。',
        effect: '由帝国机构主持物资分配与运输。',
        mutex: 'B05',
        status: 'locked',
      },
      {
        id: 'B08',
        title: '救援费用共担协议',
        icon: 'scale',
        x: 22,
        y: 765,
        requires: [['B05']],
        description: '共同救援不能只有共同的名义。各方必须议定支付、核帐与追索办法。',
        effect: '依实际签署的协议分摊费用；承诺不等于款项已到帐。',
        status: 'locked',
      },
      {
        id: 'B09',
        title: '皇家救灾专款',
        icon: 'grain',
        x: 252,
        y: 765,
        requires: [['B06']],
        description: '帝国主持援助，就要说明钱从哪里来。专款将列出来源，以及因此必须延后的一般支出。',
        effect: '设立专款与预算来源。',
        status: 'locked',
      },
      {
        id: 'B11',
        title: '跨境灾情总录',
        icon: 'scroll',
        x: 562,
        y: 765,
        requires: [['B05', 'B06']],
        description: '把实际收到的报告整理成共同依据。仍然未知的地区留白，不以整齐的帐册掩盖失联的村镇。',
        effect: '编成首版总录，明确标出未知区域。',
        status: 'locked',
      },
      {
        id: 'B12',
        title: '灾害应对常设章程',
        icon: 'star',
        x: 482,
        y: 915,
        requires: [['B10'], ['B11'], ['B08', 'B09']],
        description:
          '最初的命令都是暂准与特许。如今接济站仍在收人，港口每天要安排船位。下一批受灾者不该再等一轮御前争论。',
        effect: '常设应对制度生效；灾害、运输及收容事件继续演变。',
        status: 'locked',
      },
    ],
    summary:
      '帝国核查北境商路并冻结新增官方信用，同时保留粮食与药材豁免，著手统筹渡鸦港粮运。禁运与交涉路线尚未选定，跨境地脉灾害便迫使朝廷转向救援与民生供应。粮运统筹仍在进行；信用冻结尚未解除，对外救援也尚未获得正式授权。',
    events: [
      {
        id: 'ship-space',
        title: '渡鸦港的船位之争',
        description:
          '军需官与粮商争夺船位，港务署正在核定内陆转运配额。统筹规程尚未生效，已排定的粮船照既定安排航行。',
        steps: ['港口与粮仓名册已核定', '内陆转运配额协调中', '统筹规程等待完成'],
      },
      {
        id: 'ship-space',
        title: '渡鸦港的船位之争',
        description:
          '北境急需救援粮，帝国城市也担心缺粮。船位争议扩大为军需、民生与救援的分配问题。已离港的粮船照原目的地航行，新申请尚未核准。',
        steps: ['港口与粮仓名册已核定', '内陆转运配额协调中', '救援申请等待政策授权'],
      },
      {
        id: 'ship-space',
        title: '渡鸦港的船位之争',
        description:
          '港务署收到更多援粮意向，先行核对仓储与可用船位。救援授权尚未生效，因此仍未批准跨境出航；各方持续争取配额。',
        steps: ['港口与粮仓名册已核定', '内陆转运配额协调中', '救援申请等待政策授权'],
      },
    ],
  },
  complete: {
    first: [
      {
        id: 'A01',
        title: '北境商路总核查',
        icon: 'scroll',
        x: 482,
        y: 55,
        requires: [],
        description:
          '信用争议延烧到渡鸦港。朝廷必须先知道，帝国与北境究竟欠了彼此多少，以及哪一条商路一旦中断，会先让自己的城市缺粮。',
        effect: '核查报告呈交，取得欠款、货源与航运依赖的决策依据。',
        status: 'done',
      },
      {
        id: 'A02',
        title: '冻结新增官方信用',
        icon: 'scale',
        x: 482,
        y: 195,
        requires: [['A01']],
        description:
          '皇家印信不再为新一批北境交易背书。既有契约仍有处理窗口，但任何新的风险，都不能再由朝廷默默承担。',
        effect: '暂停新增官方担保；已签契约另行处理。',
        status: 'done',
      },
      {
        id: 'A03',
        title: '民生日用豁免表',
        icon: 'grain',
        x: 172,
        y: 335,
        requires: [['A02']],
        description:
          '边境可以停止奢侈品通行，却不能停止百姓吃饭。粮食与药材将得到明确豁免，避免地方关口自行扩大禁令。',
        effect: '公布基本粮食、药材的豁免与受理办法。',
        status: 'done',
      },
      {
        id: 'A05',
        title: '旧债另案清理',
        icon: 'scroll',
        x: 792,
        y: 335,
        requires: [['A02']],
        description:
          '旧债不会因一句冻结命令消失。朝廷将逐笔核验欠款，把真实损失、投机押注与外交筹码分开处理。',
        effect: '建立既有债务申报、核验与交涉程序。',
        status: 'done',
      },
      {
        id: 'A04',
        title: '渡鸦港粮运统筹',
        icon: 'ship',
        x: 172,
        y: 480,
        requires: [['A03']],
        description:
          '渡鸦港从不缺少帐簿，缺的是愿意对同一批粮食负责的人。港务官把延误归咎于商人，商人指向领主，领主则抱怨军方征用。朝廷将把船位、仓储与转运纳入同一份调度规程。',
        effect: '粮运统筹规程生效，指定跨部门责任；实际运粮由事件继续追踪。',
        days: 18,
        total: 30,
        status: 'done',
      },
      {
        id: 'A06',
        title: '定向禁运清单',
        icon: 'shield',
        x: 677,
        y: 480,
        requires: [['A05']],
        description: '施压必须指向能够承受压力的人。限制指定货物与交易对象，保留帝国仍然需要的商路。',
        effect: '禁运清单生效；不代表对方已经让步。',
        mutex: 'A07',
        status: 'excluded',
      },
      {
        id: 'A07',
        title: '限期交涉训令',
        icon: 'scale',
        x: 907,
        y: 480,
        requires: [['A05']],
        description: '使节带走的不只是抗议，也是期限与底线。朝廷仍为协议留出位置，但不再接受无止境的拖延。',
        effect: '授权使节依明确底线展开交涉。',
        mutex: 'A06',
        status: 'done',
      },
      {
        id: 'A08',
        title: '西境军需优先',
        icon: 'shield',
        x: 57,
        y: 625,
        requires: [['A04']],
        description: '军方要求船位先装载军需。让步的会是城市粮商，而朝廷必须承担这项选择带来的民生压力。',
        effect: '紧缺船位优先供军需调度。',
        mutex: 'A09',
        status: 'excluded',
      },
      {
        id: 'A09',
        title: '平民粮运保留额',
        icon: 'grain',
        x: 287,
        y: 625,
        requires: [['A04']],
        description: '城市的面包不能只靠军需官的余裕。朝廷将为平民粮运留出底线，让征用也必须有所节制。',
        effect: '建立民用最低运量；军需使用其余船位。',
        mutex: 'A08',
        status: 'done',
      },
      {
        id: 'A10',
        title: '过境联查规程',
        icon: 'scroll',
        x: 677,
        y: 625,
        requires: [['A06']],
        description: '同一份禁令不该在十座关口变成十种收费。联查规程将约束查验，也为被扣货物提供申诉办法。',
        effect: '统一禁运查验与申诉程序。',
        status: 'excluded',
      },
      {
        id: 'A11',
        title: '有条件恢复清算',
        icon: 'scale',
        x: 907,
        y: 625,
        requires: [['A07']],
        description: '印信可以重新落在票据上，但必须先看见对方履行承诺。清算恢复将以核验条件为限。',
        effect: '对方实际接受并履行条款后，恢复部分信用清算。',
        condition: '交涉已取得实际成果',
        status: 'done',
      },
      {
        id: 'A12',
        title: '北境贸易新秩序',
        icon: 'star',
        x: 482,
        y: 765,
        requires: [
          ['A10', 'A11'],
          ['A08', 'A09'],
        ],
        description:
          '临时措施终究需要一个终点。依所选路线确立常态贸易与粮运规则，让每一艘船不必等待新的御前命令。',
        effect: '本轮贸易与粮运制度安排告一段落；旧债回收等事件继续推进。',
        status: 'done',
      },
    ],
    second: [
      {
        id: 'A12',
        title: '北境贸易新秩序',
        icon: 'star',
        x: 482,
        y: 55,
        requires: [],
        description:
          '临时措施终究需要一个终点。依所选路线确立常态贸易与粮运规则，让每一艘船不必等待新的御前命令。',
        effect: '本轮贸易与粮运制度安排告一段落；旧债回收等事件继续推进。',
        inherited: true,
        status: 'done',
      },
      {
        id: 'C01',
        title: '帝国承运担保制度',
        icon: 'ship',
        x: 137,
        y: 235,
        requires: [['A12']],
        description: '秩序恢复后，帝国需要能够长久承担航运风险的制度。',
        effect: '建立承运担保资格与责任。',
        status: 'available',
      },
      {
        id: 'C02',
        title: '港口信用争议裁决所',
        icon: 'scale',
        x: 482,
        y: 235,
        requires: [['A12']],
        description: '让下一次欠款争议先走进裁决所，而非直接走上外交谈判桌。',
        effect: '成立裁决机构与受理程序。',
        status: 'available',
      },
      {
        id: 'C03',
        title: '内陆备援粮路',
        icon: 'grain',
        x: 827,
        y: 235,
        requires: [['A12']],
        description: '海路重新畅通，不代表帝国可以忘记断粮时的脆弱。',
        effect: '核定备援粮路及分期建设预算。',
        status: 'available',
      },
      {
        id: 'C04',
        title: '皇家承运名册',
        icon: 'scroll',
        x: 137,
        y: 415,
        requires: [['C01']],
        description: '承运资格必须看得见，也必须可以追责。',
        effect: '完成首批资格核验。',
        status: 'locked',
      },
      {
        id: 'C05',
        title: '共同仲裁席位',
        icon: 'scale',
        x: 367,
        y: 415,
        requires: [['C02']],
        description: '邀请交易对方参与仲裁，换取裁决更容易获得承认。',
        effect: '实际达成共同仲裁安排。',
        mutex: 'C06',
        status: 'locked',
      },
      {
        id: 'C06',
        title: '帝国专属裁决',
        icon: 'shield',
        x: 597,
        y: 415,
        requires: [['C02']],
        description: '由帝国掌握裁决权，承担对方可能拒绝承认结果的代价。',
        effect: '确立帝国管辖与执行程序。',
        mutex: 'C05',
        status: 'locked',
      },
      {
        id: 'C07',
        title: '地方粮仓协调章程',
        icon: 'grain',
        x: 827,
        y: 415,
        requires: [['C03']],
        description: '备援道路需要沿途粮仓愿意配合。',
        effect: '议定调拨与保管责任。',
        status: 'locked',
      },
      {
        id: 'C08',
        title: '承运风险准备金',
        icon: 'ship',
        x: 137,
        y: 595,
        requires: [['C04']],
        description: '担保需要资金，不能只靠皇家名义。',
        effect: '设立准备金与赔付边界。',
        status: 'locked',
      },
      {
        id: 'C09',
        title: '跨境票据核验',
        icon: 'scroll',
        x: 482,
        y: 595,
        requires: [['C05', 'C06']],
        description: '将所选裁决安排落实到每张票据的核验上。',
        effect: '形成票据核验程序。',
        status: 'locked',
      },
      {
        id: 'C10',
        title: '启用备援调粮',
        icon: 'grain',
        x: 827,
        y: 595,
        requires: [['C07']],
        description: '在道路与粮仓具备实际条件后，执行首轮备援调粮。',
        effect: '完成首轮调度验证。',
        condition: '道路与粮仓已具备运作条件',
        status: 'locked',
      },
      {
        id: 'C11',
        title: '帝国供应韧性章程',
        icon: 'star',
        x: 482,
        y: 775,
        requires: [['C08'], ['C09'], ['C10']],
        description: '把本期建立的担保、裁决与备援调度纳入常态运作。',
        effect: '确立多路供应与风险分担制度。',
        status: 'locked',
      },
    ],
    summary:
      '帝国以新增信用冻结促成北境清算交涉，最终在核验条件下恢复部分交易，并保留平民粮运最低配额。贸易与粮运常态规则已生效，本轮争议的制度安排告一段落；旧债实际回收与承运商履约仍持续追踪。',
    events: [
      {
        id: 'old-debts',
        title: '港口帐簿上的旧债',
        description: '清算制度已经恢复，第一批到期债款仍在核验。裁决程序生效，不代表款项已经入库。',
        steps: ['既有欠款申报完成', '核验与清偿交涉持续', '依实际到帐更新回收结果'],
      },
      {
        id: 'old-debts',
        title: '港口帐簿上的旧债',
        description: '第一批核验结果已送达商馆。部分债务人承诺分期清偿，欠款仍待实际收回；事件持续追踪。',
        steps: ['既有欠款申报完成', '核验与清偿交涉持续', '依实际到帐更新回收结果'],
      },
      {
        id: 'old-debts',
        title: '港口帐簿上的旧债',
        description: '商馆补交了第二批抵押资料，核验范围扩大。部分款项仍未到帐，既有追索工作继续。',
        steps: ['既有欠款申报完成', '核验与清偿交涉持续', '依实际到帐更新回收结果'],
      },
    ],
  },
};
